#!/bin/bash
# fetch-state-members.sh — Pull current congressional delegation from
# congress.gov API and output a draft state-context markdown file.
#
# Use this at the start of each new Congress to generate a draft
# state-context file. A human MUST verify all committee assignments
# before using the file in briefings — the congress.gov API does not
# include committee data and those must be added manually.
#
# Usage:
#   ./fetch-state-members.sh <state-code>
#
# Examples:
#   ./fetch-state-members.sh VA    # Virginia
#   ./fetch-state-members.sh NC    # North Carolina
#   ./fetch-state-members.sh PA    # Pennsylvania
#
# Requires:
#   - CONGRESS_API_KEY environment variable (free at api.congress.gov)
#   - curl and jq installed
#
# Output: Draft markdown file printed to stdout. Redirect to a file:
#   ./fetch-state-members.sh VA > state-context-va-draft.md
# Then verify and fill in committee assignments before renaming to
# state-context-va.md

set -e

STATE=${1:?Usage: $0 <state-code> (e.g. VA, NC, PA)}
STATE_UPPER=$(echo "$STATE" | tr '[:lower:]' '[:upper:]')
KEY="${CONGRESS_API_KEY:?Set CONGRESS_API_KEY environment variable. Get a free key at api.congress.gov}"

BASE="https://api.congress.gov/v3"
PARAMS="?api_key=${KEY}&format=json&limit=50"

echo "Fetching ${STATE_UPPER} delegation from congress.gov..." >&2

# Get current congress number
CONGRESS_DATA=$(curl -sf "${BASE}/congress/current${PARAMS}" 2>/dev/null) || {
  echo "Error: Could not fetch congress data. Check your API key." >&2
  exit 1
}
CONGRESS_NUM=$(echo "$CONGRESS_DATA" | jq -r '.congress.number // "119"')

# Get state members
MEMBERS=$(curl -sf "${BASE}/member?stateCode=${STATE_UPPER}&currentMember=true${PARAMS}&api_key=${KEY}&format=json" 2>/dev/null) || {
  echo "Error: Could not fetch member data." >&2
  exit 1
}

MEMBER_COUNT=$(echo "$MEMBERS" | jq '.members | length')
echo "Found ${MEMBER_COUNT} current members for ${STATE_UPPER}" >&2

# Output draft file header
cat << HEADER
# ${STATE_UPPER} Congressional Context — ${CONGRESS_NUM}th Congress
# DRAFT generated by fetch-state-members.sh on $(date +%Y-%m-%d)
# ⚠️  COMMITTEE ASSIGNMENTS ARE NOT INCLUDED — add them manually
#    before using this file in briefings.
# Sources for committee data:
#   House: clerk.house.gov/members/[member-id]
#   Senate: senate.gov/general/committee_assignments/assignments.htm
#
# After verifying, remove this header block and save as state-context-${STATE,,}.md

---

## Update Triggers

Edit this file immediately when any of the following occurs:
- A ${STATE_UPPER} member resigns, dies, or is expelled
- A special election changes a seat
- A member gains or loses a committee seat mid-Congress
- District lines change due to redistricting ruling

Full regeneration needed at start of each new Congress (January of odd years).

---

HEADER

# Separate senators from house members
SENATORS=$(echo "$MEMBERS" | jq '[.members[] | select(.terms.item[-1].chamber == "Senate")]')
HOUSE=$(echo "$MEMBERS" | jq '[.members[] | select(.terms.item[-1].chamber == "House")] | sort_by(.district | tonumber? // 0)')

echo "## Senate — ${STATE_UPPER}"
echo ""
echo "$SENATORS" | jq -r '.[] | "### Sen. \(.name)\nParty: \(.partyName)\nState: \(.state)\nURL: \(.url)\nBioguide: \(.bioguideId)\n\n**Committees:** FILL IN from senate.gov/general/committee_assignments\n\n**DC Phone:** FILL IN from .senate.gov/contact\n**Contact URL:** [lastname].senate.gov/contact\n\n---\n"'

echo ""
echo "## House — ${STATE_UPPER}"
echo ""
echo "$HOUSE" | jq -r '.[] | "### \(.state)-\(if .district then (if (.district | type) == "number" then .district | tostring else .district end) else "At-Large" end) — Rep. \(.name)\nParty: \(.partyName)\nBioguide: \(.bioguideId)\nURL: \(.url)\n\n**Committees:** FILL IN from clerk.house.gov/members/\(.bioguideId)\n\n**DC Phone:** FILL IN\n**Contact URL:** [lastname].house.gov/contact\n\n**Advocacy notes:** FILL IN\n\n---\n"'

cat << FOOTER

## Key State Resources

<!-- Replace with your state's equivalents. See references/sources-va.md for the pattern. -->

| Organization | URL | Best For |
|---|---|---|
| State Elections Authority | FILL IN | Voter registration, district maps |
| State Political Data Project | FILL IN (e.g. VPAP for VA) | District context, redistricting |
| State Attorney General | FILL IN | Legal challenges |
| State Legislature Research | FILL IN | Fiscal/policy analysis |
| State Political News | FILL IN | State-focused coverage |

---

## Delegation Summary

<!-- Fill in after completing all committee assignments above -->

| District | Member | Party | Key Committee(s) |
|----------|--------|-------|-----------------|
| Senate | [Name] | | |
| Senate | [Name] | | |
| [State]-01 | [Name] | | |
| (add rows) | | | |

*Generated: $(date +%Y-%m-%d) | Next full review: January $(( $(date +%Y) + 2 - $(date +%Y) % 2 )) (start of next Congress)*
FOOTER

echo "" >&2
echo "Draft complete. Next steps:" >&2
echo "  1. Fill in all FILL IN sections (especially committees)" >&2
echo "  2. Verify committee assignments at clerk.house.gov and senate.gov" >&2
echo "  3. Remove the draft warning header" >&2
echo "  4. Save as state-context-${STATE,,}.md" >&2
